# .github/workflows/scheduled_job.yml
name: Scheduled Hello World Job

#
# ⏰ Schedule the workflow to run every minute
# This cron expression '*/1 * * * *' means: 
# "At every minute."
# ⚠️ Note: GitHub does not guarantee exact 1-minute execution.
# In practice, it may only run every 5 minutes on free-tier.
#
on:
  schedule:
    - cron: '*/1 * * * *'

  # 🔘 Optional: Allow manual triggering from the GitHub UI
  workflow_dispatch:

jobs:
  run_scheduled_script:
    runs-on: ubuntu-latest

    steps:
      # 1. 🔄 Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # This token allows pushing back to the repo (e.g., output.json changes)
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. 🐍 Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # You can pin to a specific version like '3.10'

      # 3. 📦 Install Python dependencies
      - name: Install dependencies
        run: pip install -r req.txt

      # 4. 🚀 Run the Python script
      - name: Execute Python Script
        run: python src/main.py

      # 5. 💾 Commit and push changes (e.g., updated output.json)
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 Scheduled Action: Update output.json'
          file_pattern: 'output.json'
